In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mp
from sklearn import linear_model

In [5]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
import math
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom #average

4

In [9]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)  # cleaned the data model i.e correcting the data models then do ml
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)  #train my model with dataset
input = np.array([[3000,3.0,40]])
reg.predict(input)

C:\Users\HARI SANKAR\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [15]:
reg.coef_ #m1,m2,m3

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_  #b

np.float64(221323.0018654043)

In [18]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.0018654043

498408.2515740243

In [19]:
reg.predict([[2500,4,5]])

C:\Users\HARI SANKAR\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])